api/routes/add.py
from ..utils import *
from flask import render_template, flash, session, request, redirect, Blueprint
from ..constants import *
from . import verify_recaptcha, addPoints, verify_form
from ..factory import get_db2, get_db1

addBlueprint = Blueprint("add", __name__)


@addBlueprint.route("/add", methods=["GET", "POST"])
def add():
    if session.get("role") != 'admin':
        flash(f"You are not logged in Or not an administrator Sorry!", "error")
        return redirect("/contact")
    if request.method == "POST":
        verify_recaptcha(request.form.get("g-recaptcha-response"))
        verify_form(CreatePostForm(request.form))
        postTitle = request.form["postTitle"]
        postTags = request.form["postTags"]
        postContent = request.form["postContent"]
        postBanner = request.files["postBanner"].read()
        postCategory = request.form["postCategory"]
        print(f"postContent {postContent}")
        db_post = get_db1()
        cursor_post = db_post.cursor()
        cursor_post.execute("insert into posts(title,tags,content,banner,author,views,timeStamp,lastEditTimeStamp,category)  values(?, ?, ?, ?, ?, ?, ?, ?, ?)",
                            (postTitle, postTags, postContent, postBanner, session["userName"], 0, currentTime(), currentTime(), postCategory))
        db_post.commit()
        Log.success(f'Post: "{postTitle}" posted by "{session["userName"]}"')
        addPoints(20, session["userName"])
        flash("You earned 20 points by posting.", "success")
        return redirect("/")
    else:
        return render_template("add.html", siteKey=RECAPTCHA_SITE_KEY)

api/routes/blog.py
"""
This file contains the routes for the Flask application.

The Blueprint "index" is used to define the home page of the application.
The route "/" maps the index function to the home page.

The index function retrieves all posts from the database and passes them to the 404.html.jinja template.

The posts variable is passed to the 404.html.jinja template as a list of dictionaries.

The 404.html.jinja template displays the title and content of each post.
"""
import base64
from ..utils import Log
from flask import render_template, Blueprint, redirect
from . import get_db1
blogBlueprint = Blueprint("blog", __name__)


@blogBlueprint.route("/")
@blogBlueprint.route("/by=<by>/sort=<sort>")
def blog(by="timeStamp", sort="desc"):
    """
    This function maps the home page route ("/") to the index function.

    It retrieves all posts from the database and passes them to the 404.html.jinja template.

    The posts variable is passed to the 404.html.jinja template as a list of dictionaries.

    The 404.html.jinja template displays the title and content of each post.

    Parameters:
    by (str): The field to sort by. Options are "timeStamp", "title", "views", "category", "lastEditTimeStamp".
    sort (str): The order to sort in. Options are "asc" or "desc".

    Returns:
    The rendered template of the home page with sorted posts according to the provided sorting options.
    """

    byOptions = ["timeStamp", "title", "views", "category", "lastEditTimeStamp"]
    sortOptions = ["asc", "desc"]

    match by not in byOptions or sort not in sortOptions:
        case True:
            Log.warning(
                f"The provided sorting options are not valid: By: {by} Sort: {sort}"
            )
            return redirect("/")

    db_post = get_db1()
    cursor_post = db_post.cursor()
    cursor_post.execute(f"select * from posts order by {by} {sort}")
    posts = cursor_post.fetchall()

    for i in range(len(posts)):
        post = list(posts[i])
        base64_image = base64.b64encode(post[4]).decode('utf-8')
        post[4] = base64_image
        posts[i] = post

    match by:
        case "timeStamp":
            by = "Creation Date"
        case "lastEditTimeStamp":
            by = "Last Edit Date"
    sortName = f"{by} {sort}".title()
    Log.info(f"Sorting posts on index page by: {sortName}")
    return render_template("blog.html", posts=posts, nums=len(posts))

api/routes/contact.py
import smtplib
import ssl
from ..utils import *
from flask import render_template, flash, session, request, redirect, Blueprint, url_for
from passlib.hash import sha512_crypt as encryption
from ..constants import *
from email.message import EmailMessage
from . import verify_recaptcha, addPoints, verify_form
from ..factory import get_db2

contactBlueprint = Blueprint("contact", __name__)


@contactBlueprint.route("/contact", methods=["GET", "POST"])
def contact():
    if request.method == "POST":
        verify_recaptcha(request.form.get("g-recaptcha-response"))
        action = request.form.get('action')
        db_user = get_db2()
        cursor_user = db_user.cursor()
        if action == 'login':
            verify_form(LoginForm(request.form))
            email = request.form["email"]
            password = request.form["password"]
            cursor_user.execute("""select * from users where email = ? """, (email,))
            user = cursor_user.fetchone()
            if not user:
                flash("email not found.", "error")
            elif user[1] == session.get("userName"):
                flash("You are already logged in!", "success")
                return redirect("/contact")
            else:
                if encryption.verify(password, user[3]):
                    session["userName"] = user[1]
                    session["email"] = user[2]
                    session["role"] = user[5]
                    session["isVerified"] = user[8]
                    addPoints(1, user[1])
                    Log.success(f'USER: "{user[1]}" LOGGED IN')
                    flash(f"Welcome, {user[1]}!", "success")
                    return redirect("/contact")
                else:
                    flash("Wrong password.", "error")
        elif action == 'register':
            verify_form(SignUpForm(request.form))
            userName = request.form["userName"]
            email = request.form["email"]
            password = request.form["password"]
            passwordConfirm = request.form["passwordConfirm"]
            userName = userName.replace(" ", "")
            cursor_user.execute("select userName from users")
            users = str(cursor_user.fetchall())
            cursor_user.execute("select email from users")
            mails = str(cursor_user.fetchall())
            if userName in users and email in mails:
                flash("This username and email is unavailable.", "error")
            elif email in mails:
                flash("This email is unavailable.", "error")
            elif userName in users:
                flash("This username is unavailable.", "error")
            else:
                if passwordConfirm != password:
                    flash("Password must match.", "error")
                else:
                    if not userName.isascii():
                        flash("Username does not fit ascii charecters.", "error")
                    else:
                        password = encryption.hash(password)
                        cursor_user.execute(
                            f"""insert into users(userName,email,password,profilePicture,role,points,timeStamp,isVerified) values(?, ?, ?, ?, ?, ?, ?, ?)""",
                            (userName, email, password, f"{USER_PROFILE_PICTURE}{userName}{RADIUS_PROFILE_PICTURE}", "admin", 0, currentTime(), "False"))
                        db_user.commit()
                        session["userName"] = userName
                        session["email"] = email
                        session["role"] = "admin"
                        session["isVerified"] = "False"
                        context = (ssl.create_default_context())
                        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
                        server.ehlo()
                        server.starttls(context=context)
                        server.ehlo()
                        server.login(SMTP_MAIL, SMTP_PASSWORD)
                        mail = EmailMessage()
                        mail.set_content(f"Hi {userName}👋,\n Welcome to {APP_NAME}")
                        mail.add_alternative(
                            f"""\
                            <html>
                            <body>
                                <div
                                style="font-family: Arial, sans-serif;  max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 20px; border-radius:0.5rem;"
                                >
                                <div style="text-align: center;">
                                    <h1 style="color: #F43F5E;">
                                    Hi {userName}, <br />
                                    Welcome to {APP_NAME}!
                                    </h1>
                                    <p style="font-size: 16px;">
                                    We are glad you joined us.
                                    </p>
                                </div>
                                </div>
                            </body>
                            </html>
                        """,
                            subtype="html")
                        mail["Subject"] = (f"Welcome to {APP_NAME}!👋🏻")
                        mail["From"] = SMTP_MAIL
                        mail["To"] = email
                        try:
                            server.send_message(mail)
                        except Exception as e:
                            Log.danger(f"Incorrect email {e}")
                            flash(f"Incorrect email {e}", "error")
                            return redirect("/contact")
                        server.quit()
                        addPoints(1, userName)
                        Log.success(f'User: "{userName}" logged in')
                        flash(f"Welcome, {userName}!", "success")
                        return redirect(url_for('verifyUser.verifyUser', codeSent='10'))
        elif action == 'forget':
            verify_form(ForgetForm(request.form))
            cursor_user.execute("""select * from users where email = ? """, (request.form["email"],))
            user = cursor_user.fetchone()
            if not user:
                flash("email not found.", "error")
                return redirect("/contact")
            return redirect(url_for('verifyUser.verifyUser', codeSent='20'))
    return render_template("contact.html", siteKey=RECAPTCHA_SITE_KEY)

routes/add.py
from utils import *
from flask import render_template, flash, session, request, redirect, Blueprint, current_app
from constants import *
from routes import verify_recaptcha, verify_form
from bson import Binary
from models import Post
import base64
addBlueprint = Blueprint("add", __name__)


@addBlueprint.route("/add", methods=["GET", "POST"])
def add():
    if not session.get("isVerified"):
        flash(f"You are not logged in Or not Verified, Sorry!", "error")
        return redirect("/contact")
    if request.method == "POST":
        verify_recaptcha(request.form.get("g-recaptcha-response"))
        verify_form(CreatePostForm(request.form))
        postTitle = request.form["postTitle"]
        postTags = request.form["postTags"]
        postContent = request.form["postContent"]
        postBanner = request.files["postBanner"].read()
        postCategory = request.form["postCategory"]
        posts_collection = current_app.mongo_db['posts']
        post = Post(postTitle, postTags, postContent, postBanner, session["userName"], postCategory)
        try:
            posts_collection.insert_one(post.todict())
            flash("You earned 20 points by posting.", "success")
            return redirect("/")
        except Exception as e:
            flash(f"An error occurred while posting: {e}", "error")
    else:
        return render_template("add.html", siteKey=RECAPTCHA_SITE_KEY)

routes/single_blog.py
import base64
import smtplib
import ssl
from utils import *
from flask import render_template, flash, session, request, redirect, Blueprint, current_app
from constants import *
from email.message import EmailMessage
from routes import verify_recaptcha, verify_form, markdown_to_html
from bson import ObjectId
single_blogBlueprint = Blueprint("single_blog", __name__)


@single_blogBlueprint.route("/single_blog/<string:postID>", methods=["GET", "POST"])
def single_blog(postID):
    posts_collection = current_app.mongo_db['posts']
    comments_collection = current_app.mongo_db['comments']
    users_collection = current_app.mongo_db['users']

    # 查询特定的帖子
    post = posts_collection.find_one({"_id": ObjectId(postID)})
    if post:
        # 更新浏览次数
        posts_collection.update_one({"_id": ObjectId(postID)}, {"$inc": {"views": 1}})

        if request.method == "POST":
            if not session.get("userName"):
                flash(f"You are not logged in", "error")
                return redirect("/contact")
            verify_recaptcha(request.form.get("g-recaptcha-response"))
            verify_form(CommentForm(request.form))
            comment = request.form["comment"]
            parent_id = request.form.get("parent_id")
            to_email = post["author"]
            if parent_id:
                parent_comment = comments_collection.find_one({"id": parent_id})
                parent_user = parent_comment["user"]
                to_email = parent_user
                comments_collection.insert_one({
                    "post":postID,
                    "comment": comment,
                    "user": session["userName"],
                    "parent_id": parent_id,
                    "parent_user": parent_user,
                    "timeStamp": currentTime()
                })
            else:
                comments_collection.insert_one({
                    "post": postID,
                    "comment": comment,
                    "user": session["userName"],
                    "timeStamp": currentTime()
                })
            flash("You earned 5 points by commenting.", "success")
            user = users_collection.find_one({"userName": to_email})
            email = user["email"]
            context = ssl.create_default_context()
            server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
            server.ehlo()
            server.starttls(context=context)
            server.ehlo()
            server.login(SMTP_MAIL, SMTP_PASSWORD)
            mail = EmailMessage()
            mail.set_content(f"Hi 👋,\n {session['userName']} had give you a comment on {post['title']} ")
            mail.add_alternative(
                f"""\
                <html>
                <body>
                    <div style="font-family: Arial, sans-serif;  max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 20px; border-radius:0.5rem;">
                    <div style="text-align: center;">
                        <p style="font-size: 20px;">
                        点击 <a href="https://zhl2022.chat/single_blog/{postID}"> 这里 </a> 进行访问.
                        </p>
                    </div>
                    </div>
                </body>
                </html>
            """,
                subtype="html")
            mail["Subject"] = (f"👋🏻 {session['userName']} commented on your blog {post['title']}")
            mail["From"] = SMTP_MAIL
            mail["To"] = email
            try:
                server.send_message(mail)
            except Exception as e:
                flash(f"Comment to {parent_user} Incorrect email {e}", "error")
            server.quit()

        # 查询特定帖子的评论
        comments = list(comments_collection.find({"post": postID}).sort("timeStamp", -1))

        # 查询所有分类
        categories = list(posts_collection.aggregate([
            {"$group": {"_id": "$category", "count": {"$sum": 1}}},
            {"$sort": {"_id": 1}}
        ]))

        # 查询最近的帖子
        recent_posts = list(posts_collection.find({}, {"id": 1, "title": 1, "banner": 1, "lastEditTimeStamp": 1, "category": 1, "author": 1}).sort("lastEditTimeStamp", -1).limit(3))
        for recent_post in recent_posts:
            recent_post['_id'] = str(recent_post['_id'])
            recent_post['banner'] = base64.b64encode(recent_post['banner']).decode('utf-8')

        content = markdown_to_html(post["content"])
        return render_template("single_blog.html", postid=postID, title=post["title"], tags=post["tags"].split(','), content=content, author=post["author"], image=base64.b64encode(post["banner"]).decode('utf-8'), views=post["views"],
                               timeStamp=post["timeStamp"], lastEditTimeStamp=post["lastEditTimeStamp"],
                               comments=comments, categories=categories, enumerate=enumerate, recent_posts=recent_posts, comments_nums=len(comments), siteKey=RECAPTCHA_SITE_KEY)
    else:
        flash(f"This {postID} blog cannot be found", "error")
        return redirect("/")

templates/blog.html
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog - ZHL</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename = 'assets/images/oig3.jpg') }} ">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'assets/css/swap.css') }} ">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'assets/css/fancybox.min.css') }} ">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'assets/css/magnific-popup.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'assets/css/aos.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'assets/css/slick.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'assets/css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'assets/css/media_query.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/flash.css') }}"/>
</head>
<body>
<div class="flash-message">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul>
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
</div>
<div class="site_contain">
    <!-- ====================================== Cusrsor ===================================== -->
    <div class="cursor"></div>
    <!-- ====================================== Cursor End ===================================== -->
    <!-- ====================================== Preloader ===================================== -->
    <div class="page-loader">
        <div class="loader"></div>
        <div class="shadow"></div>
    </div>
    <!-- ====================================== Preloader End ===================================== -->
    <!-- ====================================== Main Menu ===================================== -->
    <header id="top-navbar" class="top-navbar">
        <div class="container">
            <div class="top-navbar_full">
                <div class="back-btn container3">
                    <a href="{{ url_for('blog.blog') }}">
                        <h1>
                            <mark>Blog</mark>
                        </h1>
                    </a>

                </div>
                <div class="hell">
                    <ul class="top-navbar-title">
                        <li class="menu-active"><a href="{{ url_for('blog.blog') }}">Blog</a></li>
                        <li><a href="{{ url_for('add.add') }}">Add</a></li>
                        <li><a href="{{ url_for('contact.contact') }}">Contact</a></li>
                    </ul>
{#                    <div class="input-main">#}
{#                        <input type="text" name="text" placeholder="Search" autocomplete="off">#}
{#                    </div>#}
                    <img src="{{ getProfilePicture(session.get('userName'))  or url_for('static', filename = 'assets/images/oig3.jpg') }}" alt="user-logo" class="user-logo">
                    <div class="outer-menu">
                        <input class="checkbox-toggle" type="checkbox" name="checkbox">
                        <div class="hamburger">
                            <div></div>
                        </div>
                        <!-- ====================================== Side Menu ===================================== -->
                        <div class="menu">
                            <div>
                                <nav>
                                    <div class="container">
                                        <div class="row sidemenu-main">
                                            <div class="col-lg-2">
                                                <div class="menu-text">
                                                    <div class="side-menu-text">
                                                        <p>Memu</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-7 side-menu-scroll">
                                                <div class="heading2"><a href="{{ url_for('blog.blog') }}">Blog</a></div>
                                                <div class="heading2"><a href="{{ url_for('add.add') }}">Add</a></div>
                                                <div class="heading2"><a href="{{ url_for('contact.contact') }}">Contact</a></div>
                                            </div>
                                            <div class="col-lg-3">
                                                <div class="cont-info">
                                                    <div class="item">
                                                        <p class="sub-title-address">地址</p>
                                                        <p class="geek-alto"> 南山区 <br>深圳, 中国</p>
                                                    </div>
                                                    <div class="item">
                                                        <p class="sub-title-address"> 联系 我 </p>
                                                        <p>zhanghuiliu2020@163.com</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </nav>
                            </div>
                        </div>
                        <!-- ====================================== Side Menu End===================================== -->
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section class="single-blog2-section-main overflow-hidden" id="main">
        <div class="container ">
            <p class="main-text" data-aos="fade-down">{{ get_daily_quote.translation }}</p>
            <h1 class="ui-ux JessicaBiogi blog2-main-text" data-aos="fade-down">ZHL Latest Blog</h1>
            <p class="main-text-min" data-aos="fade-up">{{ get_daily_quote.date }} total {{ nums }} 篇</p>
        </div>
    </section>
    <!-- ====================================== Blog Section One End ===================================== -->
    <!-- ======================================= Blog Section Two ================================== -->
    <section class="section-seven overflow-hidden">
        <div class="container-xxl">
            <div class="row">
                {% for post in posts %}
                    <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-6 new-img-box-main-blog new-img-box-main3"
                         data-aos="{{ "fade-up" if loop.index is odd else "fade-down" }}">
                        <img class="news-img" src="data:image/jpeg;base64,{{ post["banner"] }}" alt="news-img1"
                             onclick="window.location.href='{{ url_for('single_blog.single_blog',postID=post["_id"]) }}';">
                        <p class="date-dev">{{ post["timeStamp"] }} _ {{ post["title"] }}</p>
                        <h2 class="need-blog" onclick="window.location.href='{{ url_for('single_blog.single_blog',postID=post["_id"]) }}';">{{ post["title"] }}</h2>
                        <p class="explore-me read-more-btn">
                            <a href="{{ url_for('single_blog.single_blog',postID=post["_id"]) }}">READ MORE
                                <svg class="expo-arrow" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                     viewBox="0 0 32 32" fill="none">
                                    <g>
                                        <path d="M6.66669 16H25.3334" stroke="#FFDB59" stroke-width="2"
                                              stroke-linecap="round" stroke-linejoin="round"></path>
                                        <path d="M20 21.3333L25.3333 16" stroke="#FFDB59" stroke-width="2"
                                              stroke-linecap="round" stroke-linejoin="round"></path>
                                        <path d="M20 10.6666L25.3333 16" stroke="#FFDB59" stroke-width="2"
                                              stroke-linecap="round" stroke-linejoin="round"></path>
                                    </g>
                                </svg>
                            </a>
                        </p>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="load-more-btn-main" id="blog-load-more-btn">
            <button class="explore-btn hover-slide-right load-more-btn">
                    <span id="toggle">End!
                        <svg class="expo-arrow2" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                             viewBox="0 0 32 32" fill="none">
                            <g>
                                <path d="M6.66669 16H25.3334" stroke="#FFDB59" stroke-width="2" stroke-linecap="round"
                                      stroke-linejoin="round"></path>
                                <path d="M20 21.3333L25.3333 16" stroke="#FFDB59" stroke-width="2"
                                      stroke-linecap="round" stroke-linejoin="round"></path>
                                <path d="M20 10.6666L25.3333 16" stroke="#FFDB59" stroke-width="2"
                                      stroke-linecap="round" stroke-linejoin="round"></path>
                            </g>
                        </svg>
                    </span>
            </button>
        </div>
    </section>
    <!-- ====================================== Progress Scroll Bottom To Top ===================================== -->
    <div class="progress-wrap cursor-pointer">
        <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
            <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"/>
        </svg>
    </div>
    <!-- ====================================== Progress Scroll Bottom To Top End ===================================== -->
</div>
<script src="{{ url_for('static', filename='assets/javascript/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='assets/javascript/fancybox.min.js') }}"></script>
<script src="{{ url_for('static', filename='assets/javascript/gsap.js') }}"></script>
<script src="{{ url_for('static', filename='assets/javascript/magnific-popup.min.js') }}"></script>
<script src="{{ url_for('static', filename='assets/javascript/aos.js') }}"></script>
<script src="{{ url_for('static', filename='assets/javascript/slick.min.js') }}"></script>
<script src="{{ url_for('static', filename='assets/javascript/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='assets/javascript/script.js') }}"></script>
</body>
</html>